game.AddParticles( "particles/bo1/raygun.pcf" )
game.AddParticles( "particles/bo1/raygunmk2.pcf" )
game.AddParticles( "particles/bo1/bo1_pap_muzzle.pcf" )

PrecacheParticleSystem("pap_muzzle")
PrecacheParticleSystem("pap_flamering")
PrecacheParticleSystem("pap_heavy_flame")
PrecacheParticleSystem("pap_muzzle_big")
PrecacheParticleSystem("pap_muzzle_sparks")
PrecacheParticleSystem("pap_trail")

PrecacheParticleSystem("vortigaunt_beam_charge")
PrecacheParticleSystem("dg2_flash")
PrecacheParticleSystem("dg3_flash")
PrecacheParticleSystem("megatron_flash")
PrecacheParticleSystem("pap_flash")

PrecacheParticleSystem("raygun_splash")
PrecacheParticleSystem("raygun_splash_pap")
PrecacheParticleSystem("raygun_flash")
PrecacheParticleSystem("raygun_flash_pap")

PrecacheParticleSystem("rgmk2_flash")
PrecacheParticleSystem("rgmk2_pap_flash")
PrecacheParticleSystem("rgmk2_impact_glow")
PrecacheParticleSystem("rgmk2_pap_impact_glow")